---
- name: All VPC Playbooks
  hosts: localhost
  tasks: 


- name: Create VPC
  include: vpc.yaml

- name: Create Public Subnets
  include: public-sub.yaml

- name: Create IGW
  include: internet-gateway.yaml

- name: Create Private Subnets
  include: private-sub.yaml

- name: Create Nat Gateway
  include: nat-gateway.yaml

- name: Create Private RT
  include: route-table-priv.yaml

- name: Create Public RT
  include: route-table-pub.yaml